### ISSUE TITLE
calling getMarket trough a different application gives an error while the unit test seems to be ok

### ISSUE THREAD

**Issue by robert2411** [robert2411/cryptopia-api-client#14]
e.g request
cryptopiaPublic.getMarket("4913");
(DOT_USDT)

response
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "High" (class biz.stevens.datatypes.Market), not marked as ignorable (16 known properties: "buyVolume", "high", "open", "baseVolume", "bidPrice", "askPrice", "buyBaseVolume", "lastPrice", "label", "close", "tradePairId", "volume", "sellBaseVolume", "sellVolume", "change", "low"])
 at [Source: {"High":0.0455,"BaseVolume":35009.566,"Label":"DOT/USDT","Change":9.39,"BuyBaseVolume":17331.84,"LastPrice":0.043,"SellBaseVolume":1.2433169E7,"BuyVolume":5.010066E7,"Open":0.03930908,"BidPrice":0.04300001,"SellVolume":1249148.2,"Low":0.03850015,"Volume":808629.0,"Close":0.043,"AskPrice":0.0434,"TradePairId":4913}; line: 1, column: 15] (through reference chain: biz.stevens.datatypes.Market["High"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1489) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1467) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2896) ~[jackson-databind-2.8.10.jar:2.8.10]
	at com.fasterxml.jackson.databind.ObjectMapper$readValue$0.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133) ~[groovy-2.4.13.jar:2.4.13]
	at io.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.groovy:45) ~[json-path-3.0.6.jar:na]
	at io.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-2.4.13.jar:2.4.13]
	at io.restassured.internal.path.json.mapping.JsonObjectDeserializer.deserializeWithJackson2(JsonObjectDeserializer.groovy:98) ~[json-path-3.0.6.jar:na]
	at io.restassured.internal.path.json.mapping.JsonObjectDeserializer$deserializeWithJackson2.callStatic(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56) ~[groovy-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194) ~[groovy-2.4.13.jar:2.4.13]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:214) ~[groovy-2.4.13.jar:2.4.13]
	at io.restassured.internal.path.json.mapping.JsonObjectDeserializer.deserialize(JsonObjectDeserializer.groovy:67) ~[json-path-3.0.6.jar:na]
	at io.restassured.path.json.JsonPath.jsonStringToObject(JsonPath.java:1016) ~[json-path-3.0.6.jar:na]
	at io.restassured.path.json.JsonPath.getObject(JsonPath.java:558) ~[json-path-3.0.6.jar:na]
	at biz.stevens.exchange.CryptopiaPublicImpl.lambda$getMarket$0(CryptopiaPublicImpl.java:96) ~[cryptopia-api-client-1.0.0.jar:na]
	at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_101]
	at biz.stevens.exchange.CryptopiaPublicImpl.getMarket(CryptopiaPublicImpl.java:96) ~[cryptopia-api-client-1.0.0.jar:na]
	at biz.stevens.exchange.CryptopiaPublicImpl.getMarket(CryptopiaPublicImpl.java:102) ~[cryptopia-api-client-1.0.0.jar:na]
	at com.github.robert2411.scheduled.TradeTask.trade(TradeTask.java:30) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

**Comment by robert2411** [comment]
source of the issue:
In this example REST Assured will serialize the object to JSON since the request content-type is set to "application/json". It will first try to use Jackson if found in classpath and if not Gson will be used. If you change the content-type to "application/xml" REST Assured will serialize to XML using JAXB. If no content-type is defined REST Assured will try to serialize in the following order:

JSON using Jackson 2 (Faster Jackson (databind))
JSON using Jackson (databind)
JSON using Gson
XML using JAXB
